# Generated by Django 2.2 on 2021-03-14 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_user_followers'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile_desc',
            field=models.TextField(default=''),
        ),
    ]
