# Generated by Django 2.2 on 2021-02-28 14:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('foodie_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='recipe_ingredient',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='recipe_menus',
        ),
        migrations.AddField(
            model_name='recipe',
            name='ingredient',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, related_name='ingredient_recipes', to='foodie_app.Ingredient'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='menus',
            field=models.ManyToManyField(default='1', related_name='menu_recipes', to='foodie_app.Menu'),
        ),
        migrations.AddField(
            model_name='step',
            name='recipe',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='foodie_app.Recipe'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='creator',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, related_name='users', to='login.User'),
        ),
        migrations.AlterField(
            model_name='step',
            name='step',
            field=models.CharField(max_length=255),
        ),
    ]
