# Generated by Django 2.2 on 2021-02-14 19:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('foodie_app', '0002_ingredient_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='incredients',
        ),
        migrations.AddField(
            model_name='recipe',
            name='incredients',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='ingredients', to='foodie_app.Ingredient'),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='steps',
        ),
        migrations.AddField(
            model_name='recipe',
            name='steps',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='foodie_app.Step'),
            preserve_default=False,
        ),
    ]
