# Generated by Django 2.2 on 2021-02-28 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodie_app', '0003_auto_20210228_1012'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='source',
            field=models.CharField(default='', max_length=255),
        ),
    ]
