# Generated by Django 2.2 on 2021-02-28 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_user_followers'),
        ('foodie_app', '0004_recipe_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='users_who_favorite',
            field=models.ManyToManyField(default=0, related_name='favorite_recipes', to='login.User'),
        ),
    ]
