# Generated by Django 2.2 on 2021-02-28 20:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('foodie_app', '0005_recipe_users_who_favorite'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='menus',
        ),
        migrations.AddField(
            model_name='menu',
            name='friday',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='friday_recipes', to='foodie_app.Recipe'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='menu',
            name='monday',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='monday_recipes', to='foodie_app.Recipe'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='menu',
            name='saturday',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='saturday_recipes', to='foodie_app.Recipe'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='menu',
            name='sunday',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='sunday_recipes', to='foodie_app.Recipe'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='menu',
            name='thursday',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='thursday_recipes', to='foodie_app.Recipe'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='menu',
            name='tuesday',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='tuesday_recipes', to='foodie_app.Recipe'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='menu',
            name='wednesday',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='wednesday_recipes', to='foodie_app.Recipe'),
            preserve_default=False,
        ),
    ]
