# Generated by Django 2.2 on 2021-02-28 21:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foodie_app', '0006_auto_20210228_1456'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menu',
            name='week_end',
        ),
        migrations.RemoveField(
            model_name='menu',
            name='week_start',
        ),
    ]
