# Generated by Django 2.2 on 2021-02-24 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodie_app', '0007_auto_20210223_1611'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='desc',
            field=models.CharField(default='', max_length=255),
        ),
    ]
