# Generated by Django 2.2 on 2021-03-01 00:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_user_followers'),
        ('foodie_app', '0007_auto_20210228_1512'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopping_list_item',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='list_user', to='login.User'),
        ),
    ]
