# Generated by Django 2.2 on 2021-03-11 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_user_followers'),
        ('foodie_app', '0008_shopping_list_item_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='editor',
            field=models.ManyToManyField(default=1, related_name='menus', to='login.User'),
        ),
    ]
