# Generated by Django 2.2 on 2021-02-24 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodie_app', '0008_recipe_desc'),
    ]

    operations = [
        migrations.AddField(
            model_name='step',
            name='step_number',
            field=models.IntegerField(default=1),
        ),
    ]
