# Generated by Django 2.2 on 2021-03-12 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodie_app', '0009_menu_editor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='editor',
            field=models.ManyToManyField(default=1, related_name='editors', to='login.User'),
        ),
    ]
