# Generated by Django 2.2 on 2021-03-12 15:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_user_followers'),
        ('foodie_app', '0010_auto_20210312_0928'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menu',
            name='editor',
        ),
        migrations.AddField(
            model_name='menu',
            name='editor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='editor', to='login.User'),
        ),
    ]
