# Generated by Django 2.2 on 2021-02-27 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodie_app', '0010_auto_20210225_0936'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='quantity',
            field=models.CharField(default='', max_length=255),
        ),
    ]
