# Generated by Django 2.2 on 2021-02-27 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodie_app', '0010_auto_20210225_0936'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='step',
            name='recipies',
        ),
        migrations.AddField(
            model_name='recipe',
            name='steps',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='incredients',
            field=models.TextField(default=''),
        ),
        migrations.DeleteModel(
            name='Ingredient',
        ),
        migrations.DeleteModel(
            name='Step',
        ),
    ]
