# Generated by Django 2.2 on 2021-03-12 15:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('foodie_app', '0011_auto_20210312_0934'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='editor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='menus', to='login.User'),
        ),
    ]
