# Generated by Django 2.2 on 2021-02-27 19:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('foodie_app', '0011_auto_20210227_1337'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='user',
            new_name='creator',
        ),
        migrations.RenameField(
            model_name='recipe',
            old_name='incredients',
            new_name='recipe_ingredient',
        ),
        migrations.RenameField(
            model_name='recipe',
            old_name='menus',
            new_name='recipe_menus',
        ),
        migrations.RemoveField(
            model_name='step',
            name='recipies',
        ),
        migrations.AlterField(
            model_name='step',
            name='step',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='recipes', to='foodie_app.Recipe'),
        ),
    ]
