# Generated by Django 2.2 on 2021-02-27 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foodie_app', '0011_auto_20210227_0935'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='incredients',
            new_name='ingredients',
        ),
    ]
