# Generated by Django 2.2 on 2021-03-29 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodie_app', '0013_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='replies',
            field=models.ManyToManyField(blank=True, related_name='_message_replies_+', to='foodie_app.Message'),
        ),
    ]
