# Generated by Django 2.2 on 2021-03-30 15:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodie_app', '0014_message_replies'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='week_start',
            field=models.DateField(default=datetime.datetime.now),
        ),
    ]
