from django.urls import path

from . import views

urlpatterns = [
    path('', views.home),
    path('<int:user_id>', views.user_profile),
    path('add_recipe', views.add_recipe),
    path('new_recipe', views.new_recipe),
    path('<int:recipe_id>/delete_recipe', views.delete_recipe),
    path('recipe_<int:recipe_id>', views.recipe_page),
    path('<int:recipe_id>/edit_recipe_page', views.edit_recipe_page),
    path('<int:recipe_id>/edit_recipe', views.edit_recipe),
    path('<int:recipe_id>/add_favorite', views.add_favorite),
    path('<int:recipe_id>/remove_favorite', views.remove_favorite),
    path('menu', views.menu),
    path('create_menu', views.create_menu),
    path('edit_menu<int:menu_id>', views.edit_menu_page),
    path('<int:user_id>/edit_menu', views.edit_menu),
    path('add_item', views.add_item),
    path('<int:user_id>/delete_item/<int:item_id>', views.delete_item),
    path('<int:user_id>/remove_favorite_profile', views.remove_favorite_profile),
    path('log_off', views.log_off),
    path('<int:user_id>/settings', views.profile_settings),
    path('<int:user_id>/update_profile', views.update_profile),
    path('<int:user_id>/inbox', views.inbox),
    path('<int:user_id>/new_message', views.new_message),
    path('<int:user_id>/send_message', views.send_message),
    path('<int:user_id>/<int:message_id>/delete_message', views.delete_message),
    path('<int:user_id>/inbox/<int:message_id>', views.message),
    path('<int:user_id>/inbox/<int:message_id>/reply', views.reply),
    path('<int:user_id>/previous_menus', views.previous_menus),
    path('<int:recipe_id>/remove_favorite_home', views.remove_favorite_home),
    path('<int:recipe_id>/add_favorite_home', views.add_favorite_home),
    # path('add_ingredient', views.add_ingredient),
    # path('add_step', views.add_step),
]